import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";

type SqliteClient = InstanceType<typeof Database>;

/**
 * Baseline schema DDL. Mirrors drizzle/0000_clever_marauders.sql (generated by
 * `npm run db:generate` from lib/drizzle/schema.ts) with IF NOT EXISTS guards so
 * it is idempotent against databases created by the legacy ensureSchema path.
 *
 * Migration strategy:
 * - Every startup runs this idempotent baseline DDL, then records the baseline
 *   migration as applied in __drizzle_migrations (databases created before
 *   migrations existed are "baseline-marked" without re-running DDL).
 * - When the drizzle/ migrations folder is available (web app, dev CLI), Drizzle's
 *   migrator then applies any migrations newer than the baseline.
 * - The bundled CLI ships without the drizzle/ folder; it only gets the baseline
 *   DDL. Schema upgrades beyond the baseline are applied the next time the same
 *   database is opened by the web app (or a dev checkout).
 */
const BASELINE_DDL = `
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique_idx ON users (email);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions(user_id);

CREATE TABLE IF NOT EXISTS snippets (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  notes TEXT,
  language TEXT NOT NULL,
  code TEXT NOT NULL,
  search_text TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS snippets_user_id_idx ON snippets(user_id);

CREATE TABLE IF NOT EXISTS snippet_tags (
  id TEXT PRIMARY KEY,
  snippet_id TEXT NOT NULL REFERENCES snippets(id) ON DELETE CASCADE,
  tag TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS snippet_tags_snippet_id_idx ON snippet_tags(snippet_id);

CREATE TABLE IF NOT EXISTS attachments (
  id TEXT PRIMARY KEY,
  snippet_id TEXT NOT NULL REFERENCES snippets(id) ON DELETE CASCADE,
  storage_key TEXT NOT NULL,
  file_name TEXT NOT NULL,
  file_size INTEGER NOT NULL,
  mime_type TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS attachments_snippet_id_idx ON attachments(snippet_id);

CREATE TABLE IF NOT EXISTS pending_attachment_uploads (
  file_id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  snippet_id TEXT NOT NULL REFERENCES snippets(id) ON DELETE CASCADE,
  storage_key TEXT NOT NULL,
  file_name TEXT NOT NULL,
  file_size INTEGER NOT NULL,
  mime_type TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS api_tokens (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  token_prefix TEXT NOT NULL,
  token_hash TEXT NOT NULL,
  last_used_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS api_tokens_token_hash_unique_idx ON api_tokens (token_hash);

CREATE INDEX IF NOT EXISTS api_tokens_user_id_idx ON api_tokens(user_id);

CREATE TABLE IF NOT EXISTS browser_login_exchanges (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code_hash TEXT NOT NULL,
  encrypted_payload TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  consumed_at TEXT,
  created_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS browser_login_exchanges_code_hash_unique_idx ON browser_login_exchanges (code_hash);

CREATE INDEX IF NOT EXISTS browser_login_exchanges_user_id_idx ON browser_login_exchanges(user_id);
`;

/**
 * Fallback identity of the baseline migration, used only when the drizzle/
 * migrations folder is unavailable (bundled CLI). Whenever the folder is
 * present, the baseline identity is derived from the actual journal and
 * migration file instead (see readBaselineMigration), so regenerating
 * migrations never leaves a stale hardcoded hash behind.
 */
const FALLBACK_BASELINE_MIGRATION = {
  hash: "3c2a2f00966d2c5298322b2b44c5a8492102da21a4549dc6d9ea4ca59db0badd",
  createdAt: 1785894240139,
};

interface BaselineMigration {
  hash: string;
  createdAt: number;
}

function isJournalEntry(value: unknown): value is { tag: string; when: number } {
  return (
    typeof value === "object" &&
    value !== null &&
    "tag" in value &&
    typeof value.tag === "string" &&
    "when" in value &&
    typeof value.when === "number"
  );
}

/**
 * Derives the baseline migration identity from the migrations folder: the hash
 * is the sha256 of the first journal entry's SQL file and createdAt is the
 * journal `when`, matching how Drizzle's migrator records applied migrations.
 * Returns null when the folder or journal is missing or malformed.
 */
function readBaselineMigration(migrationsFolder: string): BaselineMigration | null {
  try {
    const journal: unknown = JSON.parse(
      readFileSync(path.join(migrationsFolder, "meta", "_journal.json"), "utf8")
    );

    if (typeof journal !== "object" || journal === null || !("entries" in journal)) {
      return null;
    }

    const { entries } = journal;

    if (!Array.isArray(entries)) {
      return null;
    }

    const first = entries[0];

    if (!isJournalEntry(first)) {
      return null;
    }

    const sql = readFileSync(path.join(migrationsFolder, `${first.tag}.sql`), "utf8");
    return { hash: createHash("sha256").update(sql).digest("hex"), createdAt: first.when };
  } catch {
    return null;
  }
}

const MIGRATIONS_TABLE_DDL = `
CREATE TABLE IF NOT EXISTS "__drizzle_migrations" (
  id SERIAL PRIMARY KEY,
  hash text NOT NULL,
  created_at numeric
);
`;

function markBaselineApplied(client: SqliteClient, baseline: BaselineMigration) {
  client
    .prepare('INSERT INTO "__drizzle_migrations" ("hash", "created_at") VALUES (?, ?)')
    .run(baseline.hash, baseline.createdAt);
}

function isCountRow(row: unknown): row is { count: number } {
  return (
    typeof row === "object" &&
    row !== null &&
    "count" in row &&
    typeof row.count === "number"
  );
}

function hasRecordedMigrations(client: SqliteClient) {
  const row: unknown = client
    .prepare('SELECT COUNT(*) AS count FROM "__drizzle_migrations"')
    .get();
  return isCountRow(row) && row.count > 0;
}

export interface InitializeSqliteSchemaOptions {
  /**
   * Path to the drizzle migrations folder (containing meta/_journal.json).
   * When omitted or unreadable, only the baseline DDL is applied.
   */
  migrationsFolder?: string;
}

/**
 * Brings a SQLite database up to date: applies the idempotent baseline schema,
 * baseline-marks legacy databases, then runs any newer Drizzle migrations when
 * the migrations folder is available.
 */
export function initializeSqliteSchema(
  client: SqliteClient,
  options: InitializeSqliteSchemaOptions = {}
) {
  client.exec(BASELINE_DDL);
  client.exec(MIGRATIONS_TABLE_DDL);

  const migrationsFolder = options.migrationsFolder;
  const journalAvailable =
    migrationsFolder !== undefined &&
    existsSync(path.join(migrationsFolder, "meta", "_journal.json"));
  const baseline =
    (migrationsFolder ? readBaselineMigration(migrationsFolder) : null) ??
    FALLBACK_BASELINE_MIGRATION;

  if (!hasRecordedMigrations(client)) {
    markBaselineApplied(client, baseline);
  }

  if (!migrationsFolder || !journalAvailable) {
    return;
  }

  migrate(drizzle({ client }), { migrationsFolder });
}

function isNameRow(row: unknown): row is { name: string } {
  return (
    typeof row === "object" &&
    row !== null &&
    "name" in row &&
    typeof row.name === "string"
  );
}

/** Test helper: list user-visible table names in the database. */
export function listTables(client: SqliteClient) {
  const rows: unknown[] = client
    .prepare("SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name")
    .all();
  return rows.filter(isNameRow).map((row) => row.name);
}
